# Generated by Django 3.1.6 on 2021-02-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="target",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.object",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="name",
            field=models.CharField(max_length=24),
        ),
    ]
