# Generated by Django 3.1.6 on 2021-02-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210211_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
